spring:
  profiles:
    active: local
  config:
    import: classpath:config/
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      client-name: ${REDIS_CLIENT_NAME}

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

jwt:
  issuer: daily-us
  secret: ${JWT_SECRET}
  access-token-expiration-seconds: 3600
  refresh-token-expiration-seconds: 1209600

management:
  endpoints:
    web:
      exposure:
        include: prometheus